# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [notifications, 100]
  - [http_request, 50]
  - [search_indexer, 30]
  - [mailer, 5]
  - [mailers, 5]
  - [default, 3]
:schedule:
  update_hot_topic_sorted_set:
    cron: "0 */1 * * *"
    class: UpdateHotTopicSortedSetWorker
    args: 7
    description: 'every 1hours run for 7 days hot topic'
  update_hot_topic_sorted_set:
    cron: "*/10 * * * *"
    class: UpdateHotTopicSortedSetWorker
    args: 1
    description: 'every 10mins run for 1 day hot topic'
